language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
script: cargo build --verbose && CARGO_BUILD_JOBS=2 cargo test --verbose
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
